import { planAPI, recordAPI } from '../../utils/api.js'

Page({
  data: {
    stateDescription: '',
    planDays: 7,
    planDaysIndex: 0,
    planDaysOptions: [
      { label: '7天', value: 7 },
      { label: '14天', value: 14 },
      { label: '21天', value: 21 },
      { label: '30天', value: 30 }
    ],
    generatedPlan: null,
    plans: [],
    records: [],
    isLoading: false,
    selectedPlanId: null
  },

  onLoad() {
    // 检查登录状态
    this.checkLoginStatus()
    this.loadPlans()
  },
  
  checkLoginStatus() {
    const token = wx.getStorageSync('auth_token')
    const userId = wx.getStorageSync('user_id')
    
    if (!token && !userId) {
      // 未登录，跳转到登录页面
      wx.redirectTo({
        url: '/pages/login/login'
      })
      return
    }
  },

  onStateDescriptionChange(e) {
    this.setData({
      stateDescription: e.detail.value
    })
  },

  onPlanDaysChange(e) {
    const index = parseInt(e.detail.value)
    this.setData({
      planDaysIndex: index,
      planDays: this.data.planDaysOptions[index].value
    })
  },

  async loadPlans() {
    try {
      const response = await planAPI.getPlans()
      this.setData({
        plans: response.plans || []
      })
    } catch (error) {
      console.error('Failed to load plans:', error)
    }
  },

  async generatePlan() {
    if (!this.data.stateDescription.trim() || this.data.isLoading) {
      if (!this.data.stateDescription.trim()) {
        wx.showToast({
          title: '请描述当前状态',
          icon: 'none'
        })
      }
      return
    }

    this.setData({
      isLoading: true
    })

    try {
      const response = await planAPI.createPlan({
        title: `[神经可塑性训练] ${this.data.planDays}天计划`,
        days: this.data.planDays,
        tasks: [] // Tasks will be generated by AI service
      })

      this.setData({
        generatedPlan: response,
        isLoading: false
      })

      await this.loadPlans()

      wx.showToast({
        title: '计划生成成功',
        icon: 'success'
      })
    } catch (error) {
      console.error('Failed to generate plan:', error)
      wx.showToast({
        title: '生成失败，请重试',
        icon: 'none'
      })
      this.setData({
        isLoading: false
      })
    }
  },

  async selectPlan(e) {
    const planId = e.currentTarget.dataset.planId
    this.setData({
      selectedPlanId: planId
    })
    await this.loadRecords(planId)
  },

  async loadRecords(planId) {
    try {
      const response = await recordAPI.getRecords(planId)
      this.setData({
        records: response.records || []
      })
    } catch (error) {
      console.error('Failed to load records:', error)
    }
  }
})