<template>
  <div class="practice-container">
    <h2>修行计划</h2>
    
    <div class="plan-generator">
      <h3>生成个性化修行计划</h3>
      <div class="form-group">
        <label>当前状态描述：</label>
        <textarea 
          v-model="stateDescription" 
          placeholder="请描述您当前的心理状态或遇到的挑战..."
          :disabled="isLoading"
        ></textarea>
      </div>
      
      <div class="form-group">
        <label>计划周期：</label>
        <select v-model.number="planDays" :disabled="isLoading">
          <option :value="7">7天</option>
          <option :value="14">14天</option>
          <option :value="21">21天</option>
          <option :value="30">30天</option>
        </select>
      </div>
      
      <button @click="generatePlan" :disabled="!stateDescription.trim() || isLoading">
        {{ isLoading ? '生成中...' : '生成计划' }}
      </button>
    </div>
    
    <div v-if="generatedPlan" class="plan-display">
      <h3>{{ generatedPlan.title }}</h3>
      <div class="plan-details">
        <div 
          v-for="task in generatedPlan.tasks" 
          :key="task.day"
          class="task-day"
        >
          <h4>第{{ task.day }}天</h4>
          <h5>{{ task.title }}</h5>
          <p>{{ task.description }}</p>
          <div class="scientific-basis" v-if="task.scientific_basis">
            <strong>科学依据：</strong>{{ task.scientific_basis }}
          </div>
        </div>
      </div>
    </div>
    
    <div v-if="plans.length > 0" class="plans-list">
      <h3>我的修行计划</h3>
      <div class="plan-cards">
        <div 
          v-for="plan in plans" 
          :key="plan.id"
          class="plan-card"
          :class="{ active: selectedPlanId === plan.id }"
          @click="selectPlan(plan.id)"
        >
          <h4>{{ plan.title }}</h4>
          <p>{{ plan.days }}天计划</p>
          <span class="plan-date">{{ new Date(plan.created_at).toLocaleDateString() }}</span>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import { ref, onMounted } from 'vue'
import { planAPI, recordAPI } from '../services/api'

export default {
  name: 'PracticeView',
  setup() {
    const stateDescription = ref('')
    const planDays = ref(7)
    const generatedPlan = ref(null)
    const plans = ref([])
    const records = ref([])
    const isLoading = ref(false)
    const selectedPlanId = ref(null)
    
    // Load plans on mount
    onMounted(async () => {
      await loadPlans()
    })
    
    const loadPlans = async () => {
      try {
        const response = await planAPI.getPlans()
        plans.value = response.data.plans || []
      } catch (error) {
        console.error('Failed to load plans:', error)
      }
    }
    
    const generatePlan = async () => {
      if (!stateDescription.value.trim() || isLoading.value) return
      
      isLoading.value = true
      try {
        // First, send a message to AI to generate the plan
        // This would typically be done through the chat API with a special prompt
        // For now, we'll create a basic plan structure
        // In production, this should call a dedicated plan generation endpoint
        
        const response = await planAPI.createPlan({
          title: `[神经可塑性训练] ${planDays.value}天计划`,
          days: planDays.value,
          tasks: [] // Tasks will be generated by AI service
        })
        
        generatedPlan.value = response.data
        await loadPlans()
      } catch (error) {
        console.error('Failed to generate plan:', error)
        alert('生成计划失败，请稍后重试')
      } finally {
        isLoading.value = false
      }
    }
    
    const loadRecords = async (planId) => {
      try {
        const response = await recordAPI.getRecords(planId)
        records.value = response.data.records || []
      } catch (error) {
        console.error('Failed to load records:', error)
      }
    }
    
    const selectPlan = (planId) => {
      selectedPlanId.value = planId
      loadRecords(planId)
    }
    
    return {
      stateDescription,
      planDays,
      generatedPlan,
      plans,
      records,
      isLoading,
      selectedPlanId,
      generatePlan,
      selectPlan
    }
  }
}
</script>

<style scoped>
.practice-container {
  max-width: 800px;
  margin: 0 auto;
  padding: 20px;
}

.plan-generator {
  background-color: #f5f5f5;
  padding: 20px;
  border-radius: 8px;
  margin-bottom: 30px;
}

.plan-generator h3 {
  margin-top: 0;
}

.form-group {
  margin-bottom: 20px;
  text-align: left;
}

.form-group label {
  display: block;
  margin-bottom: 8px;
  font-weight: bold;
}

.form-group textarea {
  width: 100%;
  padding: 12px;
  border: 1px solid #ddd;
  border-radius: 4px;
  resize: vertical;
  min-height: 100px;
  font-family: inherit;
}

.form-group select {
  padding: 8px 12px;
  border: 1px solid #ddd;
  border-radius: 4px;
  font-size: 16px;
}

button {
  background-color: #42b983;
  color: white;
  border: none;
  padding: 12px 24px;
  border-radius: 4px;
  cursor: pointer;
  font-size: 16px;
}

button:disabled {
  background-color: #ccc;
  cursor: not-allowed;
}

.plan-display {
  text-align: left;
}

.plan-details .task-day {
  background-color: #f9f9f9;
  border: 1px solid #eee;
  border-radius: 8px;
  padding: 20px;
  margin-bottom: 20px;
}

.task-day h4 {
  color: #42b983;
  margin-top: 0;
}

.task-day h5 {
  margin: 10px 0 5px;
  color: #333;
}

.scientific-basis {
  background-color: #e8f4f1;
  padding: 10px;
  border-radius: 4px;
  margin-top: 10px;
  font-size: 14px;
}

.plans-list {
  margin-top: 40px;
  text-align: left;
}

.plans-list h3 {
  margin-bottom: 20px;
  color: #42b983;
}

.plan-cards {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));
  gap: 20px;
}

.plan-card {
  background-color: #f9f9f9;
  border: 2px solid #eee;
  border-radius: 8px;
  padding: 20px;
  cursor: pointer;
  transition: all 0.3s;
}

.plan-card:hover {
  border-color: #42b983;
  box-shadow: 0 4px 12px rgba(66, 185, 131, 0.2);
}

.plan-card.active {
  border-color: #42b983;
  background-color: #e8f4f1;
}

.plan-card h4 {
  margin: 0 0 10px;
  color: #333;
}

.plan-card p {
  margin: 5px 0;
  color: #666;
}

.plan-date {
  display: block;
  margin-top: 10px;
  font-size: 12px;
  color: #999;
}
</style>